# Generated by Django 2.2.5 on 2022-07-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CASInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, max_length=100)),
                ('entry_name', models.CharField(db_index=True, max_length=100)),
                ('data_class', models.CharField(db_index=True, max_length=100)),
                ('protein_name', models.CharField(db_index=True, max_length=100)),
                ('gene_name', models.CharField(db_index=True, max_length=100)),
                ('organism', models.CharField(db_index=True, max_length=100)),
                ('taxonomy_id', models.CharField(max_length=100, null=True)),
                ('sequence_length', models.IntegerField(null=True)),
            ],
        ),
    ]
