# Generated by Django 2.2.5 on 2022-07-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CASInfo',
        ),
    ]
