# Generated by Django 2.2.5 on 2022-07-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0003_casinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinfo',
            name='organism',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
