# Generated by Django 2.2.5 on 2022-07-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0004_auto_20220706_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinfo',
            name='organism',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
