# Generated by Django 2.2.5 on 2022-07-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0005_auto_20220706_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinfo',
            name='protein_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
