# Generated by Django 2.2.5 on 2022-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0006_auto_20220706_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignSPScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain1', models.CharField(db_index=True, max_length=200)),
                ('chain2_acc', models.CharField(db_index=True, max_length=200)),
                ('chain1_len', models.IntegerField()),
                ('chain2_len', models.IntegerField()),
                ('tool', models.CharField(max_length=100)),
                ('eff_len', models.IntegerField()),
                ('RMSD', models.IntegerField()),
                ('SPe', models.IntegerField()),
                ('SPa', models.IntegerField()),
                ('SPb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlignTMScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain1', models.CharField(db_index=True, max_length=100)),
                ('chain2_acc', models.CharField(db_index=True, max_length=100)),
                ('chain1_len', models.IntegerField()),
                ('chain2_len', models.IntegerField()),
                ('align_len', models.IntegerField()),
                ('cov_1', models.IntegerField()),
                ('cov_2', models.IntegerField()),
                ('RMSD', models.IntegerField()),
                ('seq_ID', models.IntegerField()),
                ('TMscore_1', models.IntegerField()),
                ('TMscore_2', models.IntegerField()),
                ('d0_1', models.IntegerField()),
                ('d0_2', models.IntegerField()),
            ],
        ),
    ]
