# Generated by Django 2.2.5 on 2022-07-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0007_alignspscore_aligntmscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignspscore',
            name='RMSD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alignspscore',
            name='SPa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alignspscore',
            name='SPb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alignspscore',
            name='SPe',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='RMSD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='TMscore_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='TMscore_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='cov_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='cov_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='d0_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='d0_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='aligntmscore',
            name='seq_ID',
            field=models.FloatField(),
        ),
    ]
