# Generated by Django 2.2.5 on 2022-08-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0008_auto_20220716_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignspscore',
            name='seq_ID',
            field=models.FloatField(null=True),
        ),
    ]
