# Generated by Django 2.2.5 on 2022-08-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0009_alignspscore_seq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignFatcatScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain1', models.CharField(db_index=True, max_length=200)),
                ('chain2_acc', models.CharField(db_index=True, max_length=200)),
                ('chain1_len', models.IntegerField()),
                ('chain2_len', models.IntegerField()),
                ('cov1', models.FloatField()),
                ('cov2', models.FloatField()),
                ('seq_ID', models.FloatField()),
                ('similar', models.FloatField()),
                ('alignScore', models.FloatField()),
                ('tmScore', models.FloatField()),
                ('RMSD', models.FloatField()),
            ],
        ),
    ]
