# Generated by Django 2.2.5 on 2022-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr', '0010_alignfatcatscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinfo',
            name='genome_genbank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casinfo',
            name='protein_genebankID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
