broker_url ='redis://localhost:6379/0'
# broker_url ='redis://localhost:6379/0'
# result_backend = 'redis://localhost:6379/0'
result_backend = 'django-db'
# task_serializer = 'json'
# result_serializer = 'json'
# accept_content = ['json']
enable_utc = True 
TIMEZONE='Asia/Shanghai'