"""
Django settings for django_prot project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.views.decorators.csrf import csrf_exempt, csrf_protect


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1x^q9bu8+u6g9hr&q)y8ky*)0j$%=3my0zx-4ivz(=o^3-&a2w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '222.200.186.47', '222.200.186.47:9111', '222.200.186.47:9112',
                 '222.200.186.47:8080', '::1', 'localhost', '*',
                 'bioinfo-sysu.com', '0.0.0.0'
                  ]


# Application definition
# add
INSTALLED_APPS = [

    'django_celery_results',
    'crispr.apps.CrisprConfig',
    'protein.apps.ProteinConfig',
    'polls.apps.PollsConfig',
    'livereload',
    'corsheaders',
    # defualt
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [

    # default
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Django 解决跨域访问API失败问题
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # 不同主机开发，临时注释掉。发布版本要使用
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Django 解决跨域访问API失败问题 https://cloud.tencent.com/developer/article/1701482
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True  # Django 解决跨域访问API失败问题
CORS_ALLOW_HEADERS = ('*')  # Django 解决跨域访问API失败问题

# 白名单, 域名请按照前段实际配置修改
CORS_ORIGIN_WHITELIST = [
    'http://localhost:8080',
    'http://localhost',
    'http://222.200.186.47:8080',
    'http://222.200.186.47:8081',
    'http://222.200.186.156'
]
# 允许跨域使用 cookie
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'django_prot.urls'
CSRF_COOKIE_NAME = "XSRF-TOKEN"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_prot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    # "slave": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": "nongbt_db",
    #     "USER": "nongbt",
    #     "PASSWORD": "NBT9175.814@lys628",
    #     "HOST": "",
    #     "PORT": "3306",
    # },
}

# DATABASES = {
#     'default': {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "nongbt_db",
#         "USER": "root",
#         "PASSWORD": "NBT9175.814@lys628",
#         # "HOST": "localhost",
#         "HOST": "172.22.148.191",
#         "PORT": "3306",
#         # 'OPTIONS': {

#         #     'charset': 'utf8',
#         #     'collation': 'utf8_bin',
#         # },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False
TEMP_FILE_PATH = "/training/nong/web/tmp/uploads_dev"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/protein/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/training/nong/protein/db/web',
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake'
    }
}

# # 数据库缓存配置-数据库缓存 (需要手动创建cache表)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'my_cache_table',
#         'TIMEOUT': 300, #缓存保存时间 单位秒， 默认值为300，
#         'OPTIONS': {
#             'MAX_ENTRIES': 300, #缓存最大数据条数
#             'CULL_FREQUENCY': 2, #缓存条数达到最大值时，删除1/x的缓存数据
#         }
#     }

# }


CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
