# Generated by Django 2.2.5 on 2022-03-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AF_uniprot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot', models.CharField(max_length=255)),
                ('uniprot_name', models.CharField(max_length=2550)),
                ('status', models.CharField(max_length=255)),
                ('protein_names', models.CharField(max_length=2550)),
                ('gene_names', models.CharField(max_length=2550)),
                ('organism', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=1000, null=True)),
                ('gene_name', models.CharField(max_length=2550, null=True)),
                ('accession', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtCDD',
            fields=[
                ('protin_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('length', models.IntegerField(db_index=True)),
                ('cdd_ids', models.TextField()),
                ('cdd_annots', models.TextField()),
                ('cdd_notes', models.TextField()),
                ('cdd_locs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.EmailField(max_length=50)),
                ('proj_name', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=50, null=True)),
                ('tools', models.CharField(max_length=50)),
                ('params', models.TextField(max_length=10000, null=True)),
                ('upload_date', models.DateTimeField(verbose_name='date published')),
                ('running_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('run_status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitInfoNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('proj_type', models.CharField(max_length=50)),
                ('proj_name', models.CharField(max_length=50, null=True)),
                ('email_addr', models.EmailField(max_length=50, null=True)),
                ('tools', models.CharField(max_length=1000)),
                ('params', models.TextField(max_length=10000, null=True)),
                ('upload_date', models.DateTimeField(verbose_name='date published')),
                ('running_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('run_status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphfold', models.CharField(max_length=255)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.GeneInfo')),
            ],
        ),
    ]
