# Generated by Django 2.2.5 on 2022-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtCDD2_head',
            fields=[
                ('protin_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('length', models.IntegerField(db_index=True)),
                ('cdd_ids', models.TextField()),
                ('cdd_annots', models.TextField()),
                ('cdd_notes', models.TextField()),
                ('cdd_locs', models.TextField()),
            ],
        ),
    ]
