# Generated by Django 2.2.5 on 2022-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_protcdd2_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtCDDeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protin_id', models.CharField(db_index=True, max_length=200)),
                ('length', models.IntegerField(db_index=True)),
                ('cdd_id', models.CharField(db_index=True, max_length=200)),
                ('cdd_name', models.CharField(db_index=True, max_length=1000)),
                ('cdd_note', models.CharField(db_index=True, max_length=1000)),
                ('cdd_locs', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
