# Generated by Django 2.2.5 on 2022-03-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_protcddeach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protcddeach',
            old_name='cdd_locs',
            new_name='cdd_loca',
        ),
    ]
