# Generated by Django 2.2.5 on 2022-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0005_protcddeach2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDD',
            fields=[
                ('pssm', models.CharField(db_index=True, max_length=100)),
                ('cdd_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('cdd_name', models.CharField(db_index=True, max_length=255)),
                ('cdd_desc', models.TextField()),
                ('pssm_len', models.IntegerField(db_index=True)),
            ],
        ),
    ]
