# Generated by Django 2.2.5 on 2022-03-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0008_cdd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CDD',
        ),
    ]
