# Generated by Django 2.2.5 on 2022-03-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0011_nrcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nrcd',
            name='cdd_noteCat',
        ),
    ]
