# Generated by Django 2.2.5 on 2022-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0012_remove_nrcd_cdd_notecat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrcd',
            name='desc',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
