# Generated by Django 2.2.5 on 2022-03-31 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0013_auto_20220331_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrcd',
            name='cdd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd_nrcd', to='protein.CDD'),
        ),
    ]
