# Generated by Django 2.2.5 on 2022-04-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0014_auto_20220331_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrcd',
            old_name='cdd_nameCat',
            new_name='cdd_idCat',
        ),
    ]
