# Generated by Django 2.2.5 on 2022-04-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0015_auto_20220402_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrcd',
            old_name='cdd_idCat',
            new_name='cdd_nameCat',
        ),
    ]
