# Generated by Django 2.2.5 on 2022-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0016_auto_20220402_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrcd',
            name='cdd_idCat',
            field=models.TextField(null=True),
        ),
    ]
