# Generated by Django 2.2.5 on 2022-04-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0017_nrcd_cdd_idcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NrCD',
        ),
    ]
