# Generated by Django 2.2.5 on 2022-04-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0019_nrcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrInfo',
            fields=[
                ('protin_id', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('desc', models.CharField(db_index=True, max_length=1000)),
                ('length', models.IntegerField(db_index=True)),
                ('filename', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='protCDncbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd_nameCat', models.TextField()),
                ('cdd_idCat', models.TextField(null=True)),
                ('protin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrinfo_protCDncbi', to='protein.NrInfo')),
            ],
        ),
        migrations.CreateModel(
            name='protCD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(db_index=True)),
                ('pssm', models.CharField(db_index=True, max_length=100)),
                ('start', models.IntegerField(db_index=True)),
                ('end', models.IntegerField(db_index=True)),
                ('evalue', models.CharField(db_index=True, max_length=100)),
                ('biscore', models.CharField(db_index=True, max_length=100)),
                ('cdd_name', models.CharField(db_index=True, max_length=1000)),
                ('cdd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd_protCD', to='protein.CDD')),
                ('protin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrinfo_protCD', to='protein.NrInfo')),
            ],
        ),
    ]
