# Generated by Django 2.2.5 on 2022-04-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0020_nrinfo_protcd_protcdncbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrinfo',
            name='desc',
            field=models.TextField(),
        ),
    ]
