# Generated by Django 2.2.5 on 2022-04-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0021_auto_20220403_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protcdncbi',
            name='protin_id',
        ),
        migrations.DeleteModel(
            name='protCD',
        ),
        migrations.DeleteModel(
            name='protCDncbi',
        ),
    ]
