# Generated by Django 2.2.5 on 2022-04-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0023_protcd_protcdncbi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protcd',
            name='cdd_id',
        ),
        migrations.RemoveField(
            model_name='protcd',
            name='protin_id',
        ),
        migrations.RemoveField(
            model_name='protcdncbi',
            name='cdd_id',
        ),
        migrations.RemoveField(
            model_name='protcdncbi',
            name='protin_id',
        ),
        migrations.DeleteModel(
            name='NrInfo',
        ),
        migrations.DeleteModel(
            name='protCD',
        ),
        migrations.DeleteModel(
            name='protCDncbi',
        ),
    ]
