# Generated by Django 2.2.5 on 2022-04-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0030_protcd_protcdncbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdd',
            name='cdd_desc_short',
            field=models.CharField(default='', max_length=255),
        ),
    ]
