# Generated by Django 2.2.5 on 2022-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0032_auto_20220404_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdd',
            name='cdd_desc_short',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
    ]
