# Generated by Django 2.2.5 on 2022-04-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0033_auto_20220404_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protcdncbi',
            name='cdd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd_protCDncbi', to='protein.CDD'),
        ),
        migrations.CreateModel(
            name='protCDncbiCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd_nameCat', models.TextField()),
                ('cdd_idCat', models.TextField()),
                ('protin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrinfo_protCDncbi', to='protein.NrInfo')),
            ],
        ),
    ]
