# Generated by Django 2.2.5 on 2022-04-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0035_protcdncbione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='protCDncbiOne',
        ),
    ]
