# Generated by Django 2.2.5 on 2022-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0039_protcdncbione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='protCDncbi',
        ),
    ]
