# Generated by Django 2.2.5 on 2022-04-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0040_delete_protcdncbi'),
    ]

    operations = [
        migrations.CreateModel(
            name='protCDncbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd_name', models.CharField(db_index=True, max_length=255)),
                ('protin_id', models.CharField(db_index=True, max_length=200)),
                ('length', models.IntegerField(db_index=True)),
                ('pssm', models.CharField(db_index=True, max_length=100)),
                ('start', models.IntegerField(db_index=True)),
                ('end', models.IntegerField(db_index=True)),
                ('evalue', models.CharField(db_index=True, max_length=100)),
                ('biscore', models.CharField(db_index=True, max_length=100)),
                ('cdd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdd_protCDncbi', to='protein.CDD')),
            ],
        ),
    ]
