# Generated by Django 2.2.5 on 2022-04-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0041_protcdncbi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='protCDncbi',
        ),
    ]
