# Generated by Django 2.2.5 on 2022-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0044_auto_20220408_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitinfonew',
            old_name='result',
            new_name='task_status',
        ),
        migrations.AddField(
            model_name='submitinfonew',
            name='run_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
