# Generated by Django 2.2.5 on 2022-04-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0045_auto_20220408_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtCDD2_head',
        ),
    ]
