# Generated by Django 2.2.5 on 2022-04-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0046_delete_protcdd2_head'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtCDDeach2',
        ),
    ]
