# Generated by Django 2.2.5 on 2022-04-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0047_delete_protcddeach2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtCDDeach',
        ),
    ]
