# Generated by Django 2.2.5 on 2022-04-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0048_delete_protcddeach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='protCDncbiCat',
        ),
    ]
