# Generated by Django 2.2.5 on 2022-04-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0049_delete_protcdncbicat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NrCD',
        ),
    ]
