# Generated by Django 2.2.5 on 2022-04-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0053_scopecla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeCla',
        ),
    ]
