# Generated by Django 2.2.5 on 2022-08-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0056_protcdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDBentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCODE', models.CharField(max_length=20)),
                ('HEADER', models.CharField(max_length=200)),
                ('ACCESSION_DATE', models.DateTimeField()),
                ('COMPOUND', models.CharField(max_length=500)),
                ('SOURCE', models.CharField(max_length=500)),
                ('AUTHOR_LIST', models.CharField(max_length=1000)),
                ('RESOLUTION', models.CharField(max_length=500)),
                ('EXPERIMENT_TYPE', models.CharField(max_length=100)),
            ],
        ),
    ]
