# Generated by Django 2.2.5 on 2022-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0057_pdbentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdbentry',
            name='RESOLUTION',
            field=models.FloatField(),
        ),
    ]
