# Generated by Django 2.2.5 on 2023-12-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0060_repeatdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reprProtein', models.CharField(db_index=True, max_length=255)),
                ('protein', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
